### ISSUE TITLE
Does not appear to work for connections created by RestClientBuilder

### ISSUE THREAD

**Issue by plocke** [michaelrice/WeakSSL#3]
Grails version 2.3.11

**Comment by hartsock** [comment]
Happen to know where the source for the lib behind RestClientBuilder is? My guess is that they're overriding what grails does internally. I would need a sample project to even troubleshoot this.

Note: This doesn't use anything specific to Grails, it's basic Java function. If the java library you are using 1. loads _after_ this module does and 2. loads its own SSL classes then the classes implemented here would be knocked out of the JVM and wouldn't do their jobs.

**Comment by plocke** [comment]
The meat of the source is here

https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-rest-client/src/main/groovy/grails/plugins/rest/client/RestBuilder.groovy

**Comment by hartsock** [comment]
I noted some class loader magic going on there, that would do it.

**Comment by plocke** [comment]
It looks like it uses some Spring REST stuff underneath to do the work.  If you have a workaround suggestion let me know.

**Comment by hartsock** [comment]
I have literally no idea why this would break (beyond my speculation about a class loader).

**Comment by michaelrice** [comment]
Im taking this project over. Give me some time to get up to speed on the code base and I will see if I can find a fix. As for a work around if this is the builder I think it is have you tried using the flag `ignoreInvalidSSL = true` 

EDIT: Oops its not the builder I was thinking of. For some reason I thought this was using the jersey-request-builder

**Comment by michaelrice** [comment]
@plocke I have been unable to reproduce this unless I don't use the `trustAll` setting.

Here is a sample app I have created: https://github.com/michaelrice/builder_test 
as a test I am using the code in this branch so that I could see some extra logging: 
https://github.com/michaelrice/WeakSSL/tree/upgrade

If you still have the problem can you supply me with a sample app that will reproduce the errors you are having?

**Comment by plocke** [comment]
Good to see active work on the project.  I won't have a chance to look more deeply into it for a while, but you mentioned using the trustAll setting - I was not using this, just 
weakssl.trustedhosts = ['localhost'] 
as from the docs that looked like it would be sufficient and I wanted other non localhost calls to actually validate the cert as normal.  Was I misinterpreting something?

**Comment by michaelrice** [comment]
@plocke based on your feedback I just did some more digging and did find a bug in the plugin config. Right now it checks to see 

```
if (trustAll == null) { 
    trustAll =  ! Environment.PRODUCTION.equals(Environment.getCurrent())
}
```

This seems to imply that if the variable isnt set in the config, and you are not running in production mode to set the variable for you to true making it all work. The only problem with that is that trustAll will not ever be null unless it is explicitly set to null in the config. It will return a ConfigObject. I am going to fix that and see what I need to do to be able to release it to grails.org/plugins as an update. Until I get that done a work around would have to be to manually set `trustAll = true` in your config. That value could be placed inside of the development stanza of your config so that it doesnt somehow work its way into production for you.
